#!/bin/bash

function usage() {
	echo "Usage:"
	echo "	tostring {options}"
	echo "Options:"
	echo "	-n <name>   Name of C variable."
	echo "	-h          Print this help text."
}


while getopts "n:h" opt; do
	case "$opt" in
		n)
			name=$OPTARG
			;;
		h)
			usage
			exit 0
			;;
		\?)
#			echo "Invalid option: -$OPTARG\!" >&2
			usage >&2
			exit 1
			;;
		:)
#			echo "Option -$OPTARG requires an argument\!" >&2
			usage >&2
			exit 1
			;;
	esac
done

if [ -n "$name" ]; then
	echo
	echo "#ifndef __"$name"_h__"
	echo "#define __"$name"_h__"
	echo
	echo "static char const $name[]="
fi

SAVEIFS=$IFS
IFS=$'\n';
while read -r line; do
	line=$(echo -n "$line" | sed 's|	|\\t|g')
	echo "	\"$line\\n\""
done
IFS=$SAVEIFS

if [ -n "$name" ]; then
	echo "	;"
	echo
	echo "#endif"
	echo
fi

exit 0

